title: SmartSubAI Documentation
description: Advanced Subdomain Enumeration with AI-Powered Risk Assessment
theme: jekyll-theme-minimal
baseurl: "/SmartSubAI/docs"
url: "https://OCEANOFANYTHING.github.io/SmartSubAI"

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
nav:
  - title: Home
    url: /
  - title: Advanced Usage
    url: /advanced_usage

# Footer
footer:
  text: "Powered by Cohere AI"
  links:
    - text: Cohere
      url: https://cohere.com
    - text: GitHub
      url: https://github.com/yourusername/SmartSubAI 